<?php
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=data.csv');
include_once 'loginhandler.php';
include_once '../../../config.php';
$test_id="";
$lsavestatus="0";
$usertype="";
$fdate=  mysqli_real_escape_string($conn,$_GET['fd']);
$tdate=  mysqli_real_escape_string($conn,$_GET['td']);
$uid=$_SESSION['loginid'];
$roleck= mysqli_query($conn, "select user_role_code from d_user_role where user_id='$uid' and record_status='A'");
$roleckr=  mysqli_fetch_array($roleck);
$rolecd= $roleckr['user_role_code'];
$doctor_code="";
if($rolecd=='1003')
{
    $docidq=  mysqli_query($conn, "select dc.doctor_code as docid from d_chambers dc inner join d_user_chamber_mapping ducm on
dc.chamber_id=ducm.chamber_id and ducm.user_id='$uid' and dc.record_status='A' and ducm.record_status='A';");
    $docidr=  mysqli_fetch_array($docidq);
    $doctor_code=$docidr['docid'];
    $output = fopen('php://output', 'w');
    fputcsv($output, array("Doctor 24x7 (https://doctor247.in)"));
    fputcsv($output, array("Report: List Of Pateints"));
    fputcsv($output, array("Report Generated by: Doctor"));
    fputcsv($output, array("From:".$fdate,"To:".$tdate));
    fputcsv($output, array(" "));
    fputcsv($output, array('Date', 'Time Slot', 'Patient Name','Visited'));
    
        $getlistq=  mysqli_query($conn, "select dca.app_date as ad, concat(dca.app_time_from ,'-', dca.app_time_to) as ts , get_patient_name(dca.patient_id) as pn, if(dca.app_completed='Y','Yes','No') as v
 from d_chambers dc inner join d_user_chamber_mapping ducm inner join d_chamber_appointment dca on
dc.chamber_id=ducm.chamber_id and ducm.user_id='$uid' and dc.record_status='A' and ducm.record_status='A'
and dca.chamber_id=dc.chamber_id and dca.record_status='A' and dca.app_date between '$fdate' and '$tdate';");
        if(mysqli_num_rows($getlistq)>0)
        {
        
        while($getlistr= mysqli_fetch_assoc($getlistq))
        {
            fputcsv($output, $getlistr);
        }}
 else {fputcsv($output, array("No Data Found"));}       
}
else if($rolecd=='1001')
{
    $output = fopen('php://output', 'w');
    fputcsv($output, array("Doctor 24x7 (https://doctor247.in)"));
    fputcsv($output, array("Report: List Of Pateints"));
    fputcsv($output, array("Report Generated by: Admin"));
    fputcsv($output, array("From:".$fdate,"To:".$tdate));
    fputcsv($output, array(" "));
    fputcsv($output, array('Doctor','Date', 'Time Slot', 'Patient Name','Visited'));
    
        $getlistq=  mysqli_query($conn, "select get_doctor_name(dc.doctor_code) as dn, dca.app_date as ad, concat(dca.app_time_from ,'-', dca.app_time_to) as ts , get_patient_name(dca.patient_id) as pn, if(dca.app_completed='Y','Yes','No') as v
 from d_chambers dc inner join d_user_chamber_mapping ducm inner join d_chamber_appointment dca on
dc.chamber_id=ducm.chamber_id and dc.record_status='A' and ducm.record_status='A'
and dca.chamber_id=dc.chamber_id and dca.record_status='A' and dca.app_date between '$fdate' and '$tdate';");
        if(mysqli_num_rows($getlistq)>0)
        {
        
        while($getlistr= mysqli_fetch_assoc($getlistq))
        {
            fputcsv($output, $getlistr);
        }}
 else {fputcsv($output, array("No Data Found"));}  
    
}
?>