<?php
require_once '../../../dompdf/autoload.inc.php';
include_once 'loginhandler.php';
include_once '../../../config.php';


// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();



$test_id="";
$lsavestatus="0";
$usertype="";
$fdate=  mysqli_real_escape_string($conn,$_GET['fd']);
$tdate=  mysqli_real_escape_string($conn,$_GET['td']);
$uid=$_SESSION['loginid'];
$roleck= mysqli_query($conn, "select user_role_code from d_user_role where user_id='$uid' and record_status='A'");
$roleckr=  mysqli_fetch_array($roleck);
$rolecd= $roleckr['user_role_code'];
$doctor_code="";

ob_start();
?>
<html>
    <head>
        <style type="text/css">
        @page {
            margin: 0px;
        }
        * { padding: 3px; margin: 7px; }
        @font-face {
            font-family: "source_sans_proregular";           
            src: local("Source Sans Pro"), url("fonts/sourcesans/sourcesanspro-regular-webfont.ttf") format("truetype");
            font-weight: normal;
            font-style: normal;

        }        
        body{
            font-family: "source_sans_proregular", Calibri,Candara,Segoe,Segoe UI,Optima,Arial,sans-serif;            
        }
    </style>
    </head>
    <body> 
        
        
        <?php

if($rolecd=='1003')
{
    $docidq=  mysqli_query($conn, "select dc.doctor_code as docid from d_chambers dc inner join d_user_chamber_mapping ducm on
dc.chamber_id=ducm.chamber_id and ducm.user_id='$uid' and dc.record_status='A' and ducm.record_status='A';");
    $docidr=  mysqli_fetch_array($docidq);
    $doctor_code=$docidr['docid'];
    ?>
    
        
    <div style="border-bottom: 1px solid #cccccc">
    <table width='100%' border='0' cellpadding='5'>
        <tr>
            <td width='180px'><img src='../../../images/logo.png'></td>
            <td>
                <h4>https://doctor247.in</h4>
                <h5>Report: List Of Patients, Report Generated by: Doctor <br> From: <?php echo $fdate; ?> To: <?php echo $tdate; ?></h5>
        
            </td>
        </tr>
    </table>
    </div>
    
    <br>
    <table width="100%" border="1" cellspacing="0" cellpadding="3">
        <thead>
            <tr>
                <th>Date</th>
                <th>Time Slot</th>
                <th>Patient Name</th>
                <th>Visited</th>
            </tr>
        
        </thead>
        
        <tbody>
            <?php
        $getlistq=  mysqli_query($conn, "select dca.app_date as ad, concat(dca.app_time_from ,'-', dca.app_time_to) as ts , get_patient_name(dca.patient_id) as pn, if(dca.app_completed='Y','Yes','No') as v
 from d_chambers dc inner join d_user_chamber_mapping ducm inner join d_chamber_appointment dca on
dc.chamber_id=ducm.chamber_id and ducm.user_id='$uid' and dc.record_status='A' and ducm.record_status='A'
and dca.chamber_id=dc.chamber_id and dca.record_status='A' and dca.app_date between '$fdate' and '$tdate';");
        if(mysqli_num_rows($getlistq)>0)
        {
        
        while($getlistr= mysqli_fetch_array($getlistq))
        { ?>
            <tr>
                <td><?php echo $getlistr['ad'] ?> </td><td><?php echo $getlistr['ts'] ?> </td><td><?php echo $getlistr['pn'] ?> </td><td><?php echo $getlistr['v'] ?> </td>
            </tr>
            
            <?php
        }}
 else { ?> 
            <tr><td colspan="4">No Data Found</td></tr>
     <?php }  ?>
          </tbody>
    </table>  
<?php }   
else if($rolecd=='1001')
{
    ?>
    <div style="border-bottom: 1px solid #cccccc">
    <table width='100%' border='0' cellpadding='5'>
        <tr>
            <td width='180px'><img src='../../../images/logo.png'></td>
            <td>
                <h4>https://doctor247.in</h4>
                <h5>Report: List Of Patients, Report Generated by: Admin <br> From: <?php echo $fdate; ?> To: <?php echo $tdate; ?></h5>
        
            </td>
        </tr>
    </table>
    </div>
    
    <br>
    <table width="100%" border="1" cellspacing="0" cellpadding="3">
        <thead>
            <tr>
                <th>Doctor</th>
                <th>Date</th>
                <th>Time Slot</th>
                <th>Patient Name</th>
                <th>Visited</th>
            </tr>
        
        </thead>
        
        <tbody>
    
    
    <?php
    
    
        $getlistq=  mysqli_query($conn, "select get_doctor_name(dc.doctor_code) as dn, dca.app_date as ad, concat(dca.app_time_from ,'-', dca.app_time_to) as ts , get_patient_name(dca.patient_id) as pn, if(dca.app_completed='Y','Yes','No') as v
 from d_chambers dc inner join d_user_chamber_mapping ducm inner join d_chamber_appointment dca on
dc.chamber_id=ducm.chamber_id and dc.record_status='A' and ducm.record_status='A'
and dca.chamber_id=dc.chamber_id and dca.record_status='A' and dca.app_date between '$fdate' and '$tdate';");
        if(mysqli_num_rows($getlistq)>0)
        {
        
        while($getlistr= mysqli_fetch_array($getlistq))
        {?>
            <tr>
                <td><?php echo $getlistr['dn'] ?> </td><td><?php echo $getlistr['ad'] ?> </td><td><?php echo $getlistr['ts'] ?> </td><td><?php echo $getlistr['pn'] ?> </td><td><?php echo $getlistr['v'] ?> </td>
            </tr>
            
            <?php
        }}
 else {?> 
            <tr><td colspan="5">No Data Found</td></tr>
     <?php }  ?>
          </tbody>
    </table>  
<?php } ?>
    </body></html>
<?php
$html=  ob_get_clean();

$dompdf->loadHtml($html,'UTF-8');

$dompdf->set_option('defaultMediaType', 'all');
$dompdf->set_option('isFontSubsettingEnabled', true);


// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
?>